# Default values for register-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/choerodon/register-server
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  managementPort: 8000

env:
  open:
    REGISTER_SERVICE_NAMESPACE: io-choerodon

service:
  enabled: false
  name: go-register-servers
  type: ClusterIP
  port: 8000

metrics:
  path: /metrics
  group: go-register-server

logs:
  parser: docker

ingress:
  enabled: false
  host: example.com

rbac:
  create: true
  serviceAccountName: default

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 512Mi
  requests:
    # cpu: 100m
    memory: 256Mi